import { ArrowRight, CheckCircle2, HeartHandshake, Home, PawPrint, Search, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import PetCard from '../../components/pets/PetCard';
import { getPets } from '../../services/petService';
import { useEffect, useState } from 'react';

const steps = [{ icon: Search, title: 'Find your match', text: 'Explore pets and discover a companion who fits your home and lifestyle.' }, { icon: HeartHandshake, title: 'Apply with care', text: 'Share a few details about yourself through our simple adoption form.' }, { icon: Home, title: 'Welcome them home', text: 'After approval, begin a beautiful new chapter together.' }];

function HomePage() {
  const [pets, setPets] = useState([]);

  useEffect(() => {
    getPets({ status: 'Available' }).then((data) => setPets(data.pets.slice(0, 3))).catch(() => setPets([]));
  }, []);

  return (
    <>
      <section className="relative overflow-hidden bg-cream"><div className="absolute -left-20 top-20 h-64 w-64 rounded-full bg-peach/20 blur-3xl" /><div className="absolute right-0 top-0 h-80 w-80 rounded-full bg-teal/10 blur-3xl" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 sm:px-8 md:py-24 lg:grid-cols-[1.05fr_.95fr] lg:px-10"><div><p className="mb-5 inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-bold text-teal shadow-sm"><PawPrint size={16} /> Every pet deserves a loving home</p><h1 className="max-w-2xl text-5xl font-black leading-[1.06] tracking-tight text-charcoal sm:text-6xl">Give a pet a <span className="text-teal">second chance.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Find your perfect companion and give them the loving home they deserve. Every adoption starts with a small, hopeful hello.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/pets" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-teal px-6 py-3.5 font-bold text-white shadow-lg shadow-teal/20 transition hover:-translate-y-0.5 hover:bg-[#348a7a]">Find a Pet <ArrowRight size={18} /></Link><Link to="/how-it-works" className="inline-flex items-center justify-center rounded-2xl border border-teal/20 bg-white px-6 py-3.5 font-bold text-teal transition hover:bg-teal/5">How It Works</Link></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-slate-600"><span className="inline-flex items-center gap-2"><CheckCircle2 size={17} className="text-teal" />Simple application</span><span className="inline-flex items-center gap-2"><CheckCircle2 size={17} className="text-teal" />Caring shelters</span></div></div><div className="relative mx-auto w-full max-w-lg"><div className="absolute -inset-4 rounded-[2.5rem] bg-peach/25 -rotate-3" /><img className="relative aspect-[4/4.5] w-full rounded-[2rem] object-cover shadow-2xl" src="https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1000&q=85" alt="Happy dog looking at the camera" /><div className="absolute -bottom-5 -left-4 rounded-2xl bg-white p-4 shadow-lg sm:left-4"><p className="text-2xl font-black text-charcoal">500+</p><p className="text-xs font-semibold text-slate-500">Pets rescued</p></div><div className="absolute -right-2 top-12 rounded-2xl bg-charcoal p-4 text-white shadow-lg"><HeartHandshake className="text-peach" /><p className="mt-2 text-xs font-bold">Love has four paws.</p></div></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal">Meet your match</p><h2 className="mt-2 text-3xl font-black text-charcoal sm:text-4xl">Pets looking for you</h2></div><Link to="/pets" className="inline-flex items-center gap-2 font-bold text-teal hover:text-charcoal">See all pets <ArrowRight size={18} /></Link></div><div className="mt-9 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{pets.length > 0 ? pets.map((pet) => <PetCard key={pet._id} pet={pet} />) : <div className="col-span-full rounded-3xl border border-dashed border-teal/30 bg-white p-10 text-center text-slate-500">Featured pets will appear here once the database is connected.</div>}</div></section>

      <section id="how-it-works" className="bg-[#f1faf8]"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="max-w-xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal">A gentle process</p><h2 className="mt-2 text-3xl font-black text-charcoal sm:text-4xl">How adoption works</h2><p className="mt-4 leading-7 text-slate-600">We make finding a companion feel simple, thoughtful, and full of hope.</p></div><div className="mt-10 grid gap-6 md:grid-cols-3">{steps.map(({ icon: Icon, title, text }, index) => <article key={title} className="rounded-3xl bg-white p-7 shadow-sm"><span className="text-sm font-black text-peach">0{index + 1}</span><div className="mt-5 grid h-12 w-12 place-items-center rounded-2xl bg-teal/10 text-teal"><Icon size={24} /></div><h3 className="mt-5 text-xl font-extrabold text-charcoal">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>

      <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:px-10"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal">Why PawConnect</p><h2 className="mt-2 text-3xl font-black text-charcoal sm:text-4xl">A happier future begins with adoption.</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">When you adopt, you do more than welcome a pet—you create room, hope, and a new beginning for another animal in need.</p><Link to="/about" className="mt-7 inline-flex items-center gap-2 font-bold text-teal hover:text-charcoal">Learn about our mission <ArrowRight size={18} /></Link></div><div className="grid grid-cols-3 gap-3"><div className="rounded-3xl bg-peach/25 p-5"><p className="text-3xl font-black text-charcoal">500+</p><p className="mt-2 text-sm font-bold text-slate-600">Pets rescued</p></div><div className="mt-8 rounded-3xl bg-teal p-5 text-white"><p className="text-3xl font-black">320+</p><p className="mt-2 text-sm font-bold text-white/85">Adoptions</p></div><div className="rounded-3xl bg-orange-100 p-5"><p className="text-3xl font-black text-charcoal">150+</p><p className="mt-2 text-sm font-bold text-slate-600">Happy families</p></div></div></section>

      <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8 lg:px-10"><div className="overflow-hidden rounded-[2rem] bg-charcoal px-7 py-12 text-center text-white sm:px-12"><ShieldCheck className="mx-auto text-peach" size={34} /><h2 className="mt-4 text-3xl font-black sm:text-4xl">Ready to change a life?</h2><p className="mx-auto mt-4 max-w-lg text-slate-300">Your future best friend may be waiting for exactly the home you can offer.</p><Link to="/pets" className="mt-7 inline-flex items-center gap-2 rounded-2xl bg-peach px-6 py-3.5 font-bold text-charcoal transition hover:bg-white">Meet our pets <ArrowRight size={18} /></Link></div></section>
    </>
  );
}

export default HomePage;
